<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);App_Data\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.27.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AI\Services\" />
    <Folder Include="Models\Common\" />
    <Folder Include="Middleware\" />
    <Folder Include="Models\Roslyn\" />
    <Folder Include="Services\GitHub\" />
    <Folder Include="Services\AI\" />
    <Folder Include="Services\Report\" />
    <Folder Include="Services\StaticAnalysis\" />
    <Folder Include="Services\Scanner\" />
    <Folder Include="Services\Upload\" />
    <Folder Include="Workspace\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
